[mitm]
hostname=aiqicha.baidu.com

[rewrite_local]
^https:\//aiqicha.baidu.com\/usercenter\/getvipinfoajax url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/aiqicha.js
