[rewrite_local]
^https:\/\/api\.calm\.com\/me$ url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/calm.js

[mitm]
hostname =  api.calm.com