[rewrite_local]
^http[s]?:\/\/cc.lzjoy.com url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/ccguitar.js

[mitm]
hostname = cc.lzjoy.com