[mitm]
hostname = *.kakamobi.cn

[rewrite_local]
^https?:\/\/.*\.kakamobi\.cn\/api\/open url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/kakamobi.js