[rewrite_local]
^https://(.+).gotokeep.com(/athena/v5/people/my|/nuocha/plans) url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/main/quantumultx-x/scripts/keep.js

[mitm]
hostname = *.gotokeep.com
