[rewrite_local]
^https?:\/\/notability\.com\/global url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/notability.js


[mitm]
hostname = notability.com