[rewrite_local]
^https:\/\/oxfordx\.cp\.com\.cn\/api\/pay\/apple_notify url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/main/quantumultx-x/scripts/oald10.js
^https:\/\/oxadmin\.cp\.com\.cn\/api\/hot\/index url reject-dict
^https:\/\/oxadmin\.cp\.com\.cn\/api\/advertise\/banner url reject-dict


[mitm]
hostname = oxfordx.cp.com.cn