[rewrite_local]
^https?:\/\/otter-api\.codefuture\.top\/v\d\/user\/current url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/otter-life.js

[mitm]
hostname = otter-api.codefuture.top