[rewrite_local]
^http[s]s:\/\/purchase-qingtu-api\.b612kaji\.com\/v1\/purchase\/subscription\/subscriber\/status url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/qingtu.js

[mitm]
hostname = purchase-qingtu-api.b612kaji.com