[mitm]
hostname = api.sipapp.io

[rewrite_local]
^https?:\/\/api\.sipapp\.io\/[\d.]+\/trial url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/sip-colorpicker.js
