[rewrite_local]
^https:\/\/i\.weread\.qq\.com\/pay\/memberCardSummary url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/weread.js

[mitm]
hostname = i.weread.qq.com