[mitm]
hostname = *xmind.*

[rewrite_local]
^https?:\/\/(?:www\.)?xmind\..*\/.+\/(devices|token\/.+) url script-response-body https://raw.githubusercontent.com/reiy-leo/network-rules/refs/heads/main/quantumult-x/scripts/xmind.js